# Generated by Django 4.2.1 on 2023-06-01 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.IntegerField(max_length=100, primary_key=True, serialize=False, verbose_name='id')),
                ('nombre', models.CharField(max_length=20, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.IntegerField(max_length=100, primary_key=True, serialize=False, verbose_name='id')),
                ('nombre', models.CharField(max_length=80, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.IntegerField(max_length=100, primary_key=True, serialize=False, verbose_name='id')),
                ('nombre', models.CharField(max_length=40, verbose_name='nombre')),
                ('apellido', models.CharField(max_length=40, verbose_name='apellido')),
                ('telefono', models.CharField(max_length=40, verbose_name='telefono')),
                ('correo', models.CharField(max_length=40, verbose_name='correo')),
                ('password', models.CharField(max_length=40, verbose_name='password')),
                ('direccion', models.CharField(max_length=60, verbose_name='correo')),
                ('foto', models.CharField(max_length=400, verbose_name='url_foto')),
                ('id_rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.rol')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.IntegerField(max_length=100, primary_key=True, serialize=False, verbose_name='id')),
                ('fecha_creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('foto', models.CharField(max_length=400, verbose_name='url_foto')),
                ('descripcion', models.CharField(max_length=400, verbose_name='descripcion')),
                ('fecha_editado', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('servicio_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.servicio')),
                ('usu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.usuario')),
            ],
            options={
                'verbose_name': 'Publicacion',
                'verbose_name_plural': 'Publicaciones',
            },
        ),
    ]
