# Generated by Django 4.2.1 on 2023-06-01 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='foto',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='url_foto'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='direccion',
            field=models.CharField(max_length=60, verbose_name='direccion'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='url_foto'),
        ),
    ]
