# Generated by Django 4.2.1 on 2023-06-01 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0002_alter_publicacion_foto_alter_usuario_direccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='titulo',
            field=models.CharField(max_length=100, null=True, verbose_name='titulo'),
        ),
    ]
